server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Rota as chamadas (Login, Produtos, Registro do Postgres) para a API Back-end
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Todas as requisições que não forem arquivos serão direcionadas ao index.html
    # Isso garante que aplicativos SPA (como React/Vite) funcionem ao atualizar a página
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache opcional para recursos estáticos (aumenta o desempenho e poupa banda do seu VPS)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15778463";
    }
}
